# Generated by Django 4.2.6 on 2023-10-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_course_delete_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('member', 'пользователь'), ('moderator', 'модератор')], default='member', max_length=12),
        ),
    ]
