# Generated by Django 4.2.6 on 2023-10-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_payment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_payment',
            field=models.DateTimeField(verbose_name='дата оплаты'),
        ),
    ]
